== RedPen に JavaScript で機能追加

伊藤です。いままでもRedPenの機能はJavaで実装できたのですが、コンパイルが必要で気軽に機能を実装できませんでした。そこでv1.3からJavaScriptでの機能追加をサポートしました。JavaScript ベースの機能追加ではコンパイル作業は必要ありません。

本稿では前半で機能拡張で実装するメソッド群（あまり使わないのも含めて）の解説を行います。後半では解説したメソッドをもとに機能を追加してみます。

=== 実装するメソッド

RedPenで機能拡張を作成するときに利用（実装）するメソッドは二種類（validate と preValidate）に大別されます。

=== validate メソッド

validateメソッドは二種類存在します。それぞれ引数によって名前が異なります（validateSentenceとvalidateSection）。どちらのメソッドも入力（文か節）内を検査して、エラーを追加します。

RedPenは文書内の文（もしくは節）のすべてを引数にしてvalidateメソッドを呼び出します。エラーの追加はaddErrorメソッドを利用します。

==== validateSentence メソッド

validateSentenceは引数に文（Sentence）を持ちます。

==== validateSection メソッド

validateSectionは引数に節（Section）をとります。文より大きな規模のチェックを行いたいときに使用します。例えば、著しく類似した節を検知する機能（DuplicatedSection）は節単位のvalidate メソッドを利用して実装されます。

=== preValidate メソッド

preValidateメソッドはvalidateメソッドの前処理を行います。具体的にはvalidateメソッドが呼び出される前に、全ての文に対してpreValdateメソッドは適用されます。validate メソッドと同様に preValidate メソッドも引数によって二種類存在します（preValidateSentence と preVdalidateSection）。

 * preValidateSenence （文を引数にとる preValidate メソッドです）
 * preValidateSection （節を引数にとる preValidate メソッドです）

現状preValidateメソッドが必要だった機能はそれほど多くありません。RedPenが提供している機能でpreValidateを利用している数少ない機能にJapaneseStyleがあります（Java ですが）。JapaneseStyle はですます調とである調が混在していないかを検査する機能です。JapaneseStyleの実装ではpreValidateメソッドを利用して、ですます調とである調で書かれた文の出現回数をカウントしています。validateメソッドでは出現回数の少なかったほうの調を利用した文が発見されるとエラーを出力するのです。

次節ではvalidateSentenceとpreValidateSentenceを利用した機能を作成してみます。

=== NotTooKanji（漢字が多すぎる） 機能

昔文書を書いていたところある共同執筆者の方から「君の文は漢字が多すぎる」という注意を受けたことがあります。理由は漢字が多いと読みにくいというものでした。「漢字を多用しすぎないように」という規約は比較的一般的です。実際にグーグルで “漢字を多用しない” と検索してみると、いくつもの記事がヒットします。

今回開発する NotTooKanji は文書内で使用されている漢字の割合がしきい値以上の時に、エラーを出力します。preValidateSentence メソッドでは文中ので使用された漢字と、すべての文字をカウントしています。validateSentenceメソッドで漢字の割合が 50% 以上の時にエラーを出力する処理を行っています。
エラーの追加には addError メソッドを利用します（引数にはエラーメッセージと、エラーが存在する文）。またNotTooKanjiではflushedというフラグを利用してエラーを一度のみ出力しています。

[source, javascript]
----
var THRESHOLD = 0.5
var kanji_count = 0
var moji_count = 0
var flushed = false

function preValidateSentence(sentence) {
    var content = sentence.getContent();
    for (var i = 0; i <= content.length - 1; i++) {
        if(/^[\u4e00-\u9faf]+$/.test(content[i])) {
            kanji_count++
        }
        moji_count++
    }
}

function validateSentence(sentence) {
    if ((parseFloat(kanji_count) / moji_count) > THRESHOLD && flushed == false) {
        addError("文書内に漢字多すぎ。。。＞＜", sentence);
        flushed = true
    }
}
----

=== 利用してみる

以下のようにJavaScript 機能を設定に追加します。

[source, xml]
----
<redpen-conf lang="ja">
   <validators>
        <validator name="JavaScript" />
   </validators>
</redpen-conf>
----

次に上記の JavaScript ファイルを NotTooKanji.js という名前で RedPen のホームディレクトリ直下の js 以下に保存します。入力文書として以下の文を “too-much-kanji.txt” というファイル名で保存します（少々人工的な例で恐縮です）。

----
貴方の文書で漢字が多過ぎる点、気を付け給え。
----

では実行してみます。

----
$bin/redpen -c conf/redpen-conf-ja.xml too-much-kanji.txt
...
too-much-kanji.txt:1: ValidationError[JavaScript], [NotTooKanji.js] 文書内に漢字多すぎ。。。＞＜ at line: 貴方の文書で漢字が多過ぎる点、気を付け給え。
----

期待どおりにエラーが出力されました。

=== まとめ

本記事ではJavaScriptでRedPenの機能拡張を作るときに利用するメソッドの解説をしました。その後実際にメソッドを利用して機能を追加してみました。
